/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Model.Login_DAO.cad_nome;
import static View.PageInitial_GUI.lblNomePI;

/**
 *
 * @author edu
 */
public class Login_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelLogo = new org.edisoncor.gui.panel.PanelImage();
        txtEmailVerif = new org.edisoncor.gui.textField.TextFieldRound();
        txtSenhaVerif = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new org.edisoncor.gui.button.ButtonAction();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRealizarLogin = new org.edisoncor.gui.button.ButtonAction();
        btnTelaCadastro = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelNice1.setBackground(new java.awt.Color(48, 44, 44));
        panelNice1.setLayout(null);

        panelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        panelNice1.add(panelLogo);
        panelLogo.setBounds(310, 11, 150, 141);

        txtEmailVerif.setToolTipText("");
        txtEmailVerif.setName(""); // NOI18N
        txtEmailVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailVerifActionPerformed(evt);
            }
        });
        panelNice1.add(txtEmailVerif);
        txtEmailVerif.setBounds(240, 190, 294, 42);

        txtSenhaVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaVerifActionPerformed(evt);
            }
        });
        panelNice1.add(txtSenhaVerif);
        txtSenhaVerif.setBounds(240, 250, 294, 42);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Faça seu login no uHealth!");
        panelNice1.add(jLabel1);
        jLabel1.setBounds(270, 160, 244, 26);

        btnSair.setText("X");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        panelNice1.add(btnSair);
        btnSair.setBounds(726, 10, 30, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Senha");
        panelNice1.add(jLabel2);
        jLabel2.setBounds(180, 260, 50, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email");
        panelNice1.add(jLabel3);
        jLabel3.setBounds(180, 200, 50, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Não tem conta? ");
        panelNice1.add(jLabel4);
        jLabel4.setBounds(270, 360, 120, 30);

        btnRealizarLogin.setText("Entrar");
        btnRealizarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarLoginActionPerformed(evt);
            }
        });
        panelNice1.add(btnRealizarLogin);
        btnRealizarLogin.setBounds(320, 310, 116, 35);

        btnTelaCadastro.setText("Cadastre-se");
        btnTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroActionPerformed(evt);
            }
        });
        panelNice1.add(btnTelaCadastro);
        btnTelaCadastro.setBounds(390, 360, 116, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(765, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailVerifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailVerifActionPerformed

    private void txtSenhaVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaVerifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaVerifActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroActionPerformed
        dispose();
        new Cadastro_GUI().setVisible(true);
    }//GEN-LAST:event_btnTelaCadastroActionPerformed

    private void btnRealizarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarLoginActionPerformed
        dispose();
        Model.Login_DAO.realLogin();       
        lblNomePI.setText("Bem vindo, "+cad_nome);
    }//GEN-LAST:event_btnRealizarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnRealizarLogin;
    private org.edisoncor.gui.button.ButtonAction btnSair;
    private org.edisoncor.gui.button.ButtonAction btnTelaCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.panel.PanelImage panelLogo;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    public static org.edisoncor.gui.textField.TextFieldRound txtEmailVerif;
    public static org.edisoncor.gui.textField.TextFieldRound txtSenhaVerif;
    // End of variables declaration//GEN-END:variables
}
