/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author edu
 */
public class MarcarConsulta_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MarcarConsulta_GUI
     */
    public MarcarConsulta_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pessoa_BOX = new org.edisoncor.gui.comboBox.ComboBoxRound();
        nameData_TXT = new org.edisoncor.gui.textField.TextFieldRectIcon();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameConsult_TXT = new org.edisoncor.gui.textField.TextFieldRectIcon();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelNice1.setBackground(new java.awt.Color(48, 44, 44));
        panelNice1.setLayout(null);

        panelNice2.setBackground(new java.awt.Color(255, 255, 255));
        panelNice2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Marcar consulta");
        panelNice2.add(jLabel1);
        jLabel1.setBounds(80, 20, 380, 40);

        panelNice1.add(panelNice2);
        panelNice2.setBounds(20, 20, 550, 80);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data da consulta");
        panelNice1.add(jLabel2);
        jLabel2.setBounds(330, 210, 135, 30);

        Pessoa_BOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emily Silva Lima", "Gabrielle Correia Santos", "José Souza Pereira", "Breno Castro Pereira" }));
        panelNice1.add(Pessoa_BOX);
        Pessoa_BOX.setBounds(40, 170, 510, 20);

        nameData_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameData_TXTActionPerformed(evt);
            }
        });
        panelNice1.add(nameData_TXT);
        nameData_TXT.setBounds(330, 240, 180, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecione a pessoa com quem você deseja marcar a consulta:");
        panelNice1.add(jLabel3);
        jLabel3.setBounds(30, 130, 500, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome da consulta:");
        panelNice1.add(jLabel4);
        jLabel4.setBounds(30, 210, 149, 30);
        panelNice1.add(nameConsult_TXT);
        nameConsult_TXT.setBounds(30, 240, 180, 30);

        buttonAction1.setText("Voltar");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });
        panelNice1.add(buttonAction1);
        buttonAction1.setBounds(20, 295, 80, 30);

        buttonAction2.setText("Confirmar");
        panelNice1.add(buttonAction2);
        buttonAction2.setBounds(220, 290, 116, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(592, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameData_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameData_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameData_TXTActionPerformed

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        new PageInitial_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonAction1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcarConsulta_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.edisoncor.gui.comboBox.ComboBoxRound Pessoa_BOX;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static org.edisoncor.gui.textField.TextFieldRectIcon nameConsult_TXT;
    public static org.edisoncor.gui.textField.TextFieldRectIcon nameData_TXT;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    // End of variables declaration//GEN-END:variables
}
